# DO NOT CHANGE - overwritten by expeditor at build time
title = "All known products that require license acceptance, and the mapping of parent to child relationships"

[[products]]
name = "chef-infra"
pretty_name = "Chef Infra"
hab_pkg_id = "chef/chef-client"
filename = "chef_infra"
mixlib_name = "chef"
license_required_version = "15"

[[products]]
name = "inspec"
pretty_name = "InSpec"
hab_pkg_id = "chef/inspec"
filename = "inspec"

[[products]]
name = "supermarket"
pretty_name = "Supermarket"
filename = "supermarket"

[[products]]
name = "chef-server"
pretty_name = "Chef Server"
hab_pkg_id = "chef/oc_erchef"
filename = "chef_server"

[[products]]
name = "push-jobs-server"
pretty_name = "Chef Push Jobs Server"
filename = "chef_push_jobs_server"

[relationships]
"chef-infra" = ["inspec"]
"chef-server" = ["chef-infra"]
"push-jobs-server" = ["chef-infra", "chef-server"]
