source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in license-acceptance.gemspec
gemspec

group :development do
  gem "chefstyle", "1.7.5"
  gem "climate_control", "~> 0.2"
  gem "mixlib-cli", "~> 2.1"
  gem "rake", ">= 10.1.0"
  gem "rspec", "~> 3.0"
  gem "thor", ">= 0.20", "< 2.0" # validate 2.0 when it ships
end

group :debug do
  gem "pry"
  gem "pry-byebug"
  gem "rb-readline"
end
