@startuml

actor user
participant LicenseAcceptor
participant FileAcceptance
participant ArgAcceptance
participant LicensePrompt
participant HelpTextMixin

user -> LicenseAcceptor : /bin/chef
LicenseAcceptor -> FileAcceptance : ::check
FileAcceptance -> LicenseAcceptor : false
LicenseAcceptor -> ArgAcceptance : ::check
ArgAcceptance -> LicenseAcceptor : false
LicenseAcceptor -> LicensePrompt : ::request_acceptance
LicensePrompt -> LicensePrompt : ::check_for_tty
LicensePrompt -> user : accept license?
user -> LicensePrompt : yes
LicensePrompt -> FileAcceptance : ::persist
FileAcceptance -> LicensePrompt : path
LicensePrompt -> LicenseAcceptor : true

@enduml
